import type { Metadata } from "next";
import "./globals.css";
import Header from "./component/shared/header";
import Footer from "./component/shared/footer";
import AIAssistantMenu from "./component/aiAssistant";

export const metadata: Metadata = {
  title: "Zazzau Emirate e-Library",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-white`}
      >
        <Header />
        <AIAssistantMenu />
        {children}
        <Footer />
      </body>
    </html>
  );
}
